name: Deploy to Oracle
# 触发workflow的条件
on:
    push:
        # 只有main分支发生push事件时，才会触发workflow
        branches: [main]
    pull_request:
        branches: [main]

env:
    SERVER_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # 服务器私钥
    SERVER_HOST: ${{ secrets.SSH_HOST }} # 服务器IP地址
    USER_NAME: ${{ secrets.SSH_USER }} # 服务器用户名

# jobs表示执行的一项或多项任务
jobs:
    build: # 任务的job_id，具体名称自定义，这里build代表打包
        runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - run: yarn install --frozen-lockfile # optional, --immutable



            # 装依赖
            - name: Install
              run: yarn

            # 打包
            - name: Build
              run: yarn build && sudo su
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
               key: ${{ secrets.SSH_PRIVATE_KEY }}
               known_hosts: unnecessary
            - name: Deploy with rsync
              run:  sshpass -p ${{ secrets.PASSWORD }} rsync -avz -e "ssh -o StrictHostKeyChecking=no -p 22" ./dist ubuntu@${{ secrets.SSH_HOST }}:~/frontend-page/
